ERROR <PID 7542:Process-1> multiClusterLogger.runworker(): error in __main__
Traceback (most recent call last):
  File "/home/douglas/gits/kernelkernel/mycluster.py", line 318, in runmaster
    assignment_tracker=masterfile['assignment_tracker']
UnboundLocalError: local variable 'masterfile' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multicluster.py", line 62, in runworker
    mycluster.run_cluster(startname, local_test=self.local_test)
  File "/home/douglas/gits/kernelkernel/mycluster.py", line 67, in __init__
    myname,optdict_variation_list=optdict_variation_list,datagen_variation_list=datagen_variation_list)
  File "/home/douglas/gits/kernelkernel/mycluster.py", line 135, in initialize
    self.runmaster(optdict_variation_list,datagen_variation_list)
  File "/home/douglas/gits/kernelkernel/mycluster.py", line 324, in runmaster
    list_of_run_dicts=self.prep_model_list(optdict_variation_list=optdict_variation_list,datagen_variation_list=datagen_variation_list)
  File "/home/douglas/gits/kernelkernel/kernelcompare.py", line 912, in prep_model_list
    datagen_dict_list=self.build_dict_variations(datagen_dict,datagen_variation_list,verbose=1)
  File "/home/douglas/gits/kernelkernel/kernelcompare.py", line 941, in build_dict_variations
    dict_ik=self.do_dict_override(dict_ik,override_dict_ik)
  File "/home/douglas/gits/kernelkernel/kernelcompare.py", line 720, in do_dict_override
    if delete=='yes':delete=1
UnboundLocalError: local variable 'delete' referenced before assignment
